

name: UrlMintBuilder CI

on:
  push:
    branches: [ "workflow-deneme" ]
  pull_request:
    branches: [ "workflow-deneme" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ 5.0.x , 6.0.x , 7.0.x ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{matrix.dotnet-version}}

    - name: Cache Nuget Packages
      uses: actions/cache@v3
      with: 
        path: ~/.nuget/packages
        key: ${{runner.os}}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
            ${{runner.os}}-nuget-


    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
