

name: UrlMintBuilder CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        dotnet-version: [ 9.0.x ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{matrix.dotnet-version}}

    - name: Verify Code Format
      run: dotnet format --verify-no-changes


    - name: Cache Nuget Packages
      uses: actions/cache@v3
      with: 
        path: ~/.nuget/packages
        key: ${{runner.os}}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
            ${{runner.os}}-nuget-




    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test --no-build --verbosity normal



    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Start stack
      run: docker compose up -d --build 

    - name: Run K6 Load Test
      uses: grafana/k6-action@v0.3.1
      with:
        filename: k6-tests/load-test.js


    - name: Set lowercase image name
      run: |
        echo "IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to Github Container Registery
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: UrlMint/Dockerfile
        push: true
        tags: ghcr.io/${{ env.IMAGE_NAME }}:latest
